parameters:
  cmakeArgs: ''

steps:
  # Configure LLVM
  - task: CMake@1
    displayName: Configure LLVM
    inputs:
      workingDirectory: $(Build.ArtifactStagingDirectory)/llvm
      cmakeArgs:
        $(Build.SourcesDirectory)/llvm-project/llvm/
        -DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory)/install/llvm
        -DLLVM_ENABLE_PROJECTS="clang"
        -DLLVM_TARGETS_TO_BUILD="X86;AArch64"
        -DLLVM_INCLUDE_DOCS=OFF
        -DLLVM_INCLUDE_EXAMPLES=OFF
        -DLLVM_INCLUDE_GO_TESTS=OFF
        -DLLVM_INCLUDE_TOOLS=ON
        -DLLVM_INCLUDE_UTILS=OFF
        -DLLVM_INCLUDE_TESTS=OFF
        -DLLVM_ENABLE_ZLIB=OFF
        -DLLVM_ENABLE_TERMINFO=OFF
        -DLLVM_OPTIMIZED_TABLEGEN=ON
        ${{parameters.cmakeArgs}}
